version: '3.8'
services:
  php:
    image: 127.0.0.1:5000/docker_swarm/php
    build: './php'
    volumes:
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - './src:/var/www/html'
      - './nginx:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./sql/init.sql:/data/application/init.sql
      - db-data:/var/lib/mysql

volumes:
  db-data:
